// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.0
// source: helloworld/helloworld.proto

package helloworld

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	StreamHelloRequests(ctx context.Context, opts ...grpc.CallOption) (Greeter_StreamHelloRequestsClient, error)
	StreamHelloReplies(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_StreamHelloRepliesClient, error)
	SayHelloChat(ctx context.Context, opts ...grpc.CallOption) (Greeter_SayHelloChatClient, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) StreamHelloRequests(ctx context.Context, opts ...grpc.CallOption) (Greeter_StreamHelloRequestsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[0], "/helloworld.Greeter/StreamHelloRequests", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterStreamHelloRequestsClient{stream}
	return x, nil
}

type Greeter_StreamHelloRequestsClient interface {
	Send(*HelloRequest) error
	CloseAndRecv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterStreamHelloRequestsClient struct {
	grpc.ClientStream
}

func (x *greeterStreamHelloRequestsClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterStreamHelloRequestsClient) CloseAndRecv() (*HelloReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) StreamHelloReplies(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_StreamHelloRepliesClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[1], "/helloworld.Greeter/StreamHelloReplies", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterStreamHelloRepliesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_StreamHelloRepliesClient interface {
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterStreamHelloRepliesClient struct {
	grpc.ClientStream
}

func (x *greeterStreamHelloRepliesClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) SayHelloChat(ctx context.Context, opts ...grpc.CallOption) (Greeter_SayHelloChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[2], "/helloworld.Greeter/SayHelloChat", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterSayHelloChatClient{stream}
	return x, nil
}

type Greeter_SayHelloChatClient interface {
	Send(*HelloRequest) error
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterSayHelloChatClient struct {
	grpc.ClientStream
}

func (x *greeterSayHelloChatClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterSayHelloChatClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility
type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	StreamHelloRequests(Greeter_StreamHelloRequestsServer) error
	StreamHelloReplies(*HelloRequest, Greeter_StreamHelloRepliesServer) error
	SayHelloChat(Greeter_SayHelloChatServer) error
	mustEmbedUnimplementedGreeterServer()
}

// UnimplementedGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (UnimplementedGreeterServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreeterServer) StreamHelloRequests(Greeter_StreamHelloRequestsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamHelloRequests not implemented")
}
func (UnimplementedGreeterServer) StreamHelloReplies(*HelloRequest, Greeter_StreamHelloRepliesServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamHelloReplies not implemented")
}
func (UnimplementedGreeterServer) SayHelloChat(Greeter_SayHelloChatServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHelloChat not implemented")
}
func (UnimplementedGreeterServer) mustEmbedUnimplementedGreeterServer() {}

// UnsafeGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServer will
// result in compilation errors.
type UnsafeGreeterServer interface {
	mustEmbedUnimplementedGreeterServer()
}

func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {
	s.RegisterService(&Greeter_ServiceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_StreamHelloRequests_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).StreamHelloRequests(&greeterStreamHelloRequestsServer{stream})
}

type Greeter_StreamHelloRequestsServer interface {
	SendAndClose(*HelloReply) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greeterStreamHelloRequestsServer struct {
	grpc.ServerStream
}

func (x *greeterStreamHelloRequestsServer) SendAndClose(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterStreamHelloRequestsServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Greeter_StreamHelloReplies_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).StreamHelloReplies(m, &greeterStreamHelloRepliesServer{stream})
}

type Greeter_StreamHelloRepliesServer interface {
	Send(*HelloReply) error
	grpc.ServerStream
}

type greeterStreamHelloRepliesServer struct {
	grpc.ServerStream
}

func (x *greeterStreamHelloRepliesServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Greeter_SayHelloChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).SayHelloChat(&greeterSayHelloChatServer{stream})
}

type Greeter_SayHelloChatServer interface {
	Send(*HelloReply) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greeterSayHelloChatServer struct {
	grpc.ServerStream
}

func (x *greeterSayHelloChatServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterSayHelloChatServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Greeter_ServiceDesc is the grpc.ServiceDesc for Greeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamHelloRequests",
			Handler:       _Greeter_StreamHelloRequests_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamHelloReplies",
			Handler:       _Greeter_StreamHelloReplies_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SayHelloChat",
			Handler:       _Greeter_SayHelloChat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "helloworld/helloworld.proto",
}
